// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApi.Models;

#nullable disable

namespace Crapi_API.Migrations
{
    [DbContext(typeof(PlayerContext))]
    [Migration("20221005232759_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("Crapi_API.Models.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdsWatched")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AvgPlaySession")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Deaths")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DistanceClimbed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DistanceFallen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Jumps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrbsCollected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrbsSpent")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
